### ISSUE TITLE
Unknown network type: kcp  请问clash不支持mkcp 

### ISSUE THREAD

**Issue by valleyss** [Hackl0us/SS-Rule-Snippet#101]
show error:      
msg="Parse config error: Proxy 1: Unknown network type: kcp"

this is part of config 

- type: vmess
  cipher: auto
  name: tyota
  server: ************
  port: "63820"
  uuid: b**********************
  alterId: "233"
  network: kcp
  tls: true

dose clash  dont Support kcp or tcp ，even mkcp or kcp both dont work。if i am set network as  "ws" do not have problem

**Comment by CyberKoo** [comment]
不支持，当前clash对vmess的只支持只有tcp和ws

**Comment by valleyss** [comment]
> 不支持，当前clash对vmess的只支持只有tcp和ws
thanks
