### ISSUE TITLE
skype

### ISSUE THREAD

**Issue by samxyzabc** [Hackl0us/SS-Rule-Snippet#102]
我用clashx默认配置，并没有使用这里的这个文件，不知道为什么skype无法接收消息，有时候消息也无法发送。
请教下，谢谢！

**Comment by Hackl0us** [comment]
抱歉，本人不使用 Skype，如果通话质量不稳定可以尝试让 Skype 相关域名和 IP 段走代理再观察。
如果不是本项目规则导致的问题，我很难给出具体结论，抱歉。
