### ISSUE TITLE
支持 Quantumult 引用规则

### ISSUE THREAD

**Issue by hitsmaxft** [Hackl0us/SS-Rule-Snippet#103]
https://github.com/Hackl0us/SS-Rule-Snippet/blob/master/LAZY_RULES/Quantumult.conf

希望提供仅提供 rule  纯净规则, 不包含 [server] 等等配置项

这是官方的例子
https://raw.githubusercontent.com/crossutility/Quantumult-X/master/filter.txt

这样子可以作为分流规则(remote-filter) 引用, 自动更新合并, 不用手动复制到配置中.

**Comment by Hackl0us** [comment]
非常感谢，下一次更新中我会支持这一特性。
