### ISSUE TITLE
使用LAZY_RULES导致bilibili访问极度缓慢问题

### ISSUE THREAD

**Issue by i5ean** [Hackl0us/SS-Rule-Snippet#107]
由于规则里面没有把bilibili的一个播放需要用的域名  bilivideo.com DIRECT掉
会导致访问bilibili异常缓慢卡顿，无法正常播放视频

经测试添加  - DOMAIN-SUFFIX,bilivideo.com,DIRECT
即可恢复正常

**Comment by DiexMi** [comment]
借楼一用，有一个我常用的看漫画的网站也被代理了导致进不去，希望写入直连
DOMAIN-SUFFIX,manhuagui.com,DIRECT

**Comment by Hackl0us** [comment]
@i5ean 感谢反馈，我会在下个版本加入这个域名的直连策略。

@DiexMi 您可以在自定义规则区域加入这两个域名的直连。可以使用提供的捷径配合生成规则～因为这个漫画网站貌似不是大众需求。非常抱歉
