### ISSUE TITLE
加载捷径缓慢

### ISSUE THREAD

**Issue by yuehun1224** [Hackl0us/SS-Rule-Snippet#116]
近几天发现安装超过 5 MB 的捷径非常缓慢，甚至经常失败。查了一下似乎是因为 cvws.icloud-content.com 这个域名的访问出了问题。该域名匹配了 Apple-direct.list 里的 DOMAIN-SUFFIX,icloud-content.com 这条规则。建议将 cvws.icloud-content.com 添加到 Apple-proxy.list 中，即可解决该问题。·

**Comment by Hackl0us** [comment]
非常感谢提供这条规则，下次更新会加入这个域名。感谢！
