### ISSUE TITLE
规则：请求添加 netmarble.com 代理规则

### ISSUE THREAD

**Issue by betaxab** [Hackl0us/SS-Rule-Snippet#124]
### 简介：

游戏名称：`七大罪：光与暗之交战` 英文名：`7DS`
域名：`*.netmarble.com`
子域：nanagb.gcdn.netmarble.com mobileauth-rest.netmarble.com netmarbleslog.netmarble.com ltm.netmarble.com marbleproduct.netmarble.com mobileauth-global.netmarble.com

### 描述：

七大罪：光与暗之交战 是一个 Android 平台 Google Play 商店上的，剧情卡牌类游戏。这个游戏必须让它的域名走代理才能连接到服务器，否则就会提示网络错误，在国内无法连接上。所以请求将 `netmarble.com` 以 DOMAIN-SUFFIX 方式，添加进代理列表中，谢谢。

**Comment by Hackl0us** [comment]
您好，非常感谢您提供这个规则。
但是我不肯定这条规则是否被大众广泛需要，希望可以加入自定义规则列表内。

如果有任何问题请继续回复这个 Issue，谢谢
