### ISSUE TITLE
请问什么时候适配新版 Clash Premium 规则？

### ISSUE THREAD

**Issue by betaxab** [Hackl0us/SS-Rule-Snippet#126]
现在 Clash Premium 已经改了规则格式，并支持规则集，请问什么时候适配一下？谢谢。

**Comment by Hackl0us** [comment]
我会在下一次更新中适配这一规则，非常感谢！

**Comment by betaxab** [comment]
mode: rule rule 应为小写。

**Comment by Hackl0us** [comment]
> mode: rule rule 应为小写。

感谢，已经更正。

**Comment by elonzh** [comment]
补一下配置文档： https://github.com/Dreamacro/clash/wiki/premium-core-features#rule-providers

**Comment by Hackl0us** [comment]
已经完成 Clash Premium 的规则适配，如果有任何问题请重新开启本 Issue。感谢 @betaxab @elonzh 两位帮忙。
