### ISSUE TITLE
请求更新下spotify的额外规则

### ISSUE THREAD

**Issue by caserangle** [Hackl0us/SS-Rule-Snippet#128]
用UWP听歌情况下，歌曲缓冲走audio-ak-spotify-com.akamaized.net。导致直连。希望开发者更新下spotify的规则，我个人写了下，希望添加下。
  - DOMAIN-SUFFIX,pscdn.co,Proxy
  - DOMAIN-SUFFIX,scdn.co,Proxy
  - DOMAIN-SUFFIX,spotify.com,Proxy
  - DOMAIN-SUFFIX,spoti.fi,Proxy
  - DOMAIN-KEYWORD,spotify.com,Proxy
  - DOMAIN-KEYWORD,-spotify-com,Proxy
  - DOMAIN-SUFFIX,audio-akp-bbr-spotify-com.akamaized.net,Proxy
  - DOMAIN-SUFFIX,audio4-ak-spotify-com.akamaized.net,Proxy
  - DOMAIN-SUFFIX,audio-ak-spotify-com.akamaized.net,Proxy
  - DOMAIN-SUFFIX,heads-ak-spotify-com.akamaized.net,Proxy

**Comment by lbylbtlbylbt** [comment]
Spotify并不需要代理，可以直连的吧。我这边都是把它的cdn全部排除，电脑端直接在软件设置里设置无代理。

**Comment by caserangle** [comment]
主要是直连效果有时候会变差，白天还好，晚上就经常能碰到效果差的情况。（运营商为北京联通）。

**Comment by Hackl0us** [comment]
akamaized.net 是一个 CDN 域名，但是这个域名在国内的连接效果似乎非常不好，需要走代理才能解决问题。

非常感谢上面三位的讨论和反馈问题，我已经部分采纳，将这个 CDN 相关域名纳入代理列表中。
