### ISSUE TITLE
访问罗技的网站几乎打不开 全局就没有问题

### ISSUE THREAD

**Issue by DaisukiOshino** [Hackl0us/SS-Rule-Snippet#133]
使用的是Clash
https://www.logitech.com.cn/zh-cn
https://www.logitechg.com.cn/zh-cn

**Comment by Hackl0us** [comment]
Clash 中，中文规则的第一条就是 .cn 的域名全部直连。我这边测试了一下，我在访问你提供的网站时，工具判定的是直连，而且可以成功访问。请看下图。请检查你的规则是否有改动过，或者是否改动了 hosts

![image](https://user-images.githubusercontent.com/10215166/99926237-fd5eae00-2d7b-11eb-8489-36f1d92f2f55.png)
