### ISSUE TITLE
surge mac v3 无法喝l2tp共存

### ISSUE THREAD

**Issue by doolindalton** [Hackl0us/SS-Rule-Snippet#137]
请问surge mac 怎么和l2tp（添加静态路由，用于公司内网）共存呢，共同开启时无法同时使用。
解决的话可以捐赠或者答谢吗？

**Comment by Hackl0us** [comment]
非常抱歉，我们有办法在这件事情上帮助到你。因为我没有这方面的需求，而且 macOS Big Sur 更新后让这个需求的实现变得更加困难。
不妨去看看 Surge 的论坛或者给 Surge 的支持写邮件看看能否有更好的解决方案。
