### ISSUE TITLE
希望可以把Apple news加到代理规则中

### ISSUE THREAD

**Issue by ispumpkin** [Hackl0us/SS-Rule-Snippet#138]
你好，希望apple news可以加到代理规则中。
类似这个https://github.com/h2y/Shadowrocket-ADBlock-Rules/issues/205

**Comment by Hackl0us** [comment]
Apple News 我会作为单独的规则片段或模块存在，因为需要让 Apple 的地图定位域名走代理，可能对于不需要 Apple News 的用户来说体验会不好。

**Comment by Hackl0us** [comment]
已经添加相关规则集，请注意看 基础规则集/AppleNews解锁 的上方3行注意事项。
