### ISSUE TITLE
希望添加`googleapis.com`这个后缀

### ISSUE THREAD

**Issue by YunShengTeng** [Hackl0us/SS-Rule-Snippet#139]
访问某些网站时，响应很慢，调试发现，其网站的css或字体使用了`googleapis.com`这个cdn地址，导致响应很慢或无反应。

**Comment by Hackl0us** [comment]
懒人规则里面已经有一条是 DOMAIN-KEYWORD, google, Proxy 因此你提及的这个域名是走代理的，请检查自己的规则是不是有问题。
