### ISSUE TITLE
规则问题

### ISSUE THREAD

**Issue by Zheng-Shuo** [Hackl0us/SS-Rule-Snippet#140]
好，
我发现规则中已经存在"- DOMAIN,safebrowsing.googleapis.com,DIRECT"这条规则了，但是每次都还是会先走一个"DOMAIN-KEYWORD"的规则，推测是"- DOMAIN-KEYWORD,google,Proxy"这条，导致经常会偷跑十几G甚至更多的流量，请问这个是规则的问题还是设置的问题，麻烦帮忙看一下，谢谢
效果如下图：
<img width="1210" alt="1603333546638993" src="https://user-images.githubusercontent.com/21071040/97155953-02e2cb80-17b1-11eb-925b-5652f56bb08f.png">

**Comment by Hackl0us** [comment]
您好，我觉得这个问题应该是软件的问题。
对于正常的代理工具规则来说，应该是按照从上至下的顺序去匹配规则，Apple 的规则在最上方因此会优先匹配这条规则才对。我放了一张我代理工具的截图，你可以看一下～

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/10215166/99924194-2bd88b00-2d74-11eb-935c-8da42c3dcd6e.png">
