### ISSUE TITLE
Surge 3的捷径，正则匹配需要更新一下

### ISSUE THREAD

**Issue by deepcoldy** [Hackl0us/SS-Rule-Snippet#142]
根据最新的
[surge 3.conf](https://github.com/Hackl0us/SS-Rule-Snippet/blob/master/LAZY_RULES/Surge/Surge%203.conf)

![image](https://user-images.githubusercontent.com/10922642/100043336-2ba9bf80-2e48-11eb-98d8-7ab34e1b58e3.png)

替换[Proxy]和[Proxy Group]的正则
`\[Proxy\][\S\s]* ProxySOCKS5TLS, SSproxy`
需要更新为
`\[Proxy\][\S\s]* ProxyTrojan, ProxySnell`

**Comment by Hackl0us** [comment]
感谢指正，已经更新。

https://www.icloud.com/shortcuts/b890bec91f644dd9aea74bebd831024b
