### ISSUE TITLE
建议删除 Shadowrocket 配置文件中 bypass-tun 的 0.0.0.0/8

### ISSUE THREAD

**Issue by microka** [Hackl0us/SS-Rule-Snippet#146]
Shadowrocket TF 最新版 2.1.72 (1197) + iOS 14.3 (iPhone 12)，使用贵站提供的 Shadowrocket.conf 配置文件，Shadowrocket 开启连接后 iOS 状态栏下拉后没有 VPN 图标（已检查 Shadowrocket 中没有开启「隐藏 VPN 图标」选项）。经反馈，作者称删掉 bypass-tun 里的 0.0.0.0/8 即可恢复正常显示 VPN 图标（此前版本的 Shadowrocket 会自动将配置文件中的 0.0.0.0/8 主动删掉，因此以前不会出现 VPN 图标被隐藏的问题）。
因此建议 Hackl0us 删除 Shadowrocket.conf 中 bypass-tun 的 0.0.0.0/8

**Comment by Hackl0us** [comment]
感谢建议，已经解决。
