### ISSUE TITLE
支持lean的openwrt就好了

### ISSUE THREAD

**Issue by wonathan** [Hackl0us/SS-Rule-Snippet#152]

**Comment by wonathan** [comment]
ShadowSocksR Plus+ 设置 ，GFWList更新URL    能贴上就很棒了

**Comment by Hackl0us** [comment]
Lean 的 OpenWRT 可以尝试编译 OpenClash 进去，我感觉这样效果更好一些。

因为 Clash 支持规则更加灵活。
