### ISSUE TITLE
请问如何分设备全局代理？电视盒子走代理，手机不走代理

### ISSUE THREAD

**Issue by clacf** [Hackl0us/SS-Rule-Snippet#153]
我的理解是不是把写电视盒子的IP给绑定在bind-address? 如果是的话，要是涉及到多个设备是用分号隔开吗？

# 允许局域网的连接（可用来共享代理）
allow-lan: true
bind-address: "*"
# 此功能仅在 allow-lan 设置为 true 时生效，支持三种参数：
# "*"                           绑定所有的 IP 地址
# 192.168.122.11                绑定一个的 IPv4 地址
# "[aaaa::a8aa:ff:fe09:57d8]"   绑定一个 IPv6 地址

**Comment by betaxab** [comment]
这里绑定的是本机的IP地址，没法单独指定。如果你想分设备，建议购买软路由一般都有这种功能。

**Comment by Hackl0us** [comment]
`bind-address` 指的是本机监听，和你说的不是一个事情。

Clash 的规则中，有类规则是 `SRC-IP-CIDR,192.168.1.201/32,DIRECT` 意思是任何来自于 192.168.1.201 IP 地址的流量均走直连。

你可以同时用 DHCP 或静态 IP 的方式固定你希望不走代理的设备的 IP，然后配合这条规则大概可以实现你希望的效果。
