### ISSUE TITLE
请问iOS15_Weather_AQI_US是否支持天气变化推送通知

### ISSUE THREAD

**Issue by yuhangrao** [Hackl0us/SS-Rule-Snippet#178]
在tg频道上看到了脚本似乎支持通过Surge推送空气质量和天气变化通知，但使用脚本后并未看到相关功能，还是需要手动修改脚本开启呢？
![IMG_0739(20210915-153544)](https://user-images.githubusercontent.com/28585220/133390964-176b28a3-5b31-4590-8649-be60b8006fb0.PNG)

**Comment by love4taylor** [comment]
>**后续开发计划**

**Comment by yuhangrao** [comment]
> 后续开发计划

那是很久很久以前的消息了，后面更新很多次了

**Comment by love4taylor** [comment]
并不冲突，你自己翻相关 commit 看看。
