### ISSUE TITLE
关于fake-ip filter的建议

### ISSUE THREAD

**Issue by srk24** [Hackl0us/SS-Rule-Snippet#188]
b站 - '*.mcdn.bilivideo.cn'这个站点端口太多了，建议加入filter

**Comment by Hackl0us** [comment]
感谢补充

**Comment by kamingchan** [comment]
加入fake-ip-filter的原因是？

**Comment by Abinthur** [comment]
求问QuantumultX是否也可以添加这一filter？

**Comment by srk24** [comment]
> 加入fake-ip-filter的原因是？

尽量减慢fakeip pool的消耗速度

**Comment by kamingchan** [comment]
thanks, it makes sense.
