### ISSUE TITLE
项目还在更新吗？

### ISSUE THREAD

**Issue by qurge** [Hackl0us/SS-Rule-Snippet#220]

**Comment by SZP1206** [comment]
我记得有段时间突然很多规则都宣布停止维护，个人猜测应该是接到相关通知或者被喝茶了吧……
用这个吧[Shadowrocket 规则](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever)

**Comment by Hackl0us** [comment]
> 我记得有段时间突然很多规则都宣布停止维护，个人猜测应该是接到相关通知或者被喝茶了吧…… 用这个吧[Shadowrocket 规则](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever)

抱歉，我很安全，没有喝茶什么的。我只是在找时间重构这个项目，希望使用一份模板生成兼容多个规则的工具。
因为目前工作 + 学业过于繁忙，实在抱歉没有及时更新。 @mtgq

**Comment by qurge** [comment]
> > 我记得有段时间突然很多规则都宣布停止维护，个人猜测应该是接到相关通知或者被喝茶了吧…… 用这个吧[Shadowrocket 规则](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever)
> 
> 抱歉，我很安全，没有喝茶什么的。我只是在找时间重构这个项目，希望使用一份模板生成兼容多个规则的工具。 因为目前工作 + 学业过于繁忙，实在抱歉没有及时更新。 @mtgq

向大佬致敬
