### ISSUE TITLE
使用规则后微博的图片貌似很难载入

### ISSUE THREAD

**Issue by OiCkilL** [Hackl0us/SS-Rule-Snippet#24]
使用规则后微博的图片貌似很难载入

**Comment by Hackl0us** [comment]
问题已经了解，我会排查问题。但是普遍来看，没有用户反映这个问题。
我能问一下您使用的微博客户端和代理工具是什么吗？

**Comment by OiCkilL** [comment]
Mac 下浏览器的微博，观察了下貌似是因为 DNS 被自动选择为国外的了。虾米也有类似的问题，CDN 被解释到虾米在美国的服务器了。

**Comment by Hackl0us** [comment]
`xiami.net` 的问题已经更新规则解决，但是您提到的新浪微博加载速度慢我表示有点疑惑。
因为有一条规则是`DOMAIN-SUFFIX,cn,DIRECT`，新浪微博的图床是 sinaimg.cn，理论这条规则可以被匹配。如果您确认您的配置文件没有问题，请尝试在微博相关规则后面添加上 `force-remote-dns`，排除是 DNS 污染的问题（尽管微博被 DNS 污染很罕见）。

**Comment by OiCkilL** [comment]
挺奇怪的，这几个国内域名真的被国外 DNS 解释了，现在用的版本是 2.7.1。
<img width="1193" alt="2018-04-27 4 52 01" src="https://user-images.githubusercontent.com/613988/39353796-5a12ebb0-4a3b-11e8-900b-cf3458c7d7ba.png">
<img width="1193" alt="2018-04-27 4 51 27" src="https://user-images.githubusercontent.com/613988/39353798-5a49d97c-4a3b-11e8-91af-65b25d1804c1.png">
<img width="1193" alt="2018-04-27 4 51 34" src="https://user-images.githubusercontent.com/613988/39353799-5baaa472-4a3b-11e8-85bd-bbaec574dec5.png">

**Comment by Hackl0us** [comment]
我看到了，你尝试清除一下系统的 DNS 缓存（图片的右下角），根据这片教程清空对应 macOS 版本的 DNS 系统缓存 https://help.dreamhost.com/hc/en-us/articles/214981288-Flushing-your-DNS-cache-in-Mac-OS-X-and-Linux 。

操作完成后，再观察一下状况。因为我用的规则和你是一样的，我的解析完全正确，而且这种情况从来没有听说过其他人反映过。

**Comment by OiCkilL** [comment]
最好我还是找了个折中的方法，加了 host 来指定部分国内域名走国内 DNS
`[Host]
t.cn = server:1.1.1.1
*.aliyun.com = server:119.29.29.29
*.alicdn.com = server:119.29.29.29
*.taobao.com = server:119.29.29.29
*.jd.com = server:119.29.29.29
*.tmall.com = server:119.29.29.29
*.xiami.net = server:119.29.29.29
*.weibo.com = server:119.29.29.29
*.bilibili.com = server:119.29.29.29
*.ykimg.com = server:119.29.29.29
*.youku.com = server:119.29.29.29
*.cn = server:119.29.29.29`

**Comment by Hackl0us** [comment]
我觉得可能是你对 路由器做什么更改了，这个问题我也不是很清楚。而且目前只有您一个人遇到了……确实蛮奇怪的。如果您刷新了 DNS 服务也没有任何改善，我也没有任何办法帮助你更好地处理问题。
