### ISSUE TITLE
Snapchat 的IP段可以告知下吗

### ISSUE THREAD

**Issue by aishuidedabai** [Hackl0us/SS-Rule-Snippet#25]

**Comment by Hackl0us** [comment]
Snapchat 的  IP 短需要去 IP 库查询，但是理论来讲没有必要。
因为最后一条的 GeoIP 可以帮助你把所有的国外 IP 段都代理了，理论来讲不影响使用。

**Comment by aishuidedabai** [comment]
影响使用，用的免费版mmdb，Snapchat添加了geoip无法发送消息
