### ISSUE TITLE
quantumult如何更新filter规则？

### ISSUE THREAD

**Issue by 2lei** [Hackl0us/SS-Rule-Snippet#26]
除了reset后，重新导入规则，订阅的规则更新了，如何让app filter同步更新？

**Comment by Hackl0us** [comment]
因为我本人不经常使用 Quantumult，所以这个问题我没有太明确的答案。
但是我测试的过程中发现，可以直接通过规则向左滑动，然后 Replace 所有 Filter。还有一个复选框是 File Action，但是我并没有完全理解这个功能的意义。也希望您帮助测试一下。
具体操作请参见：https://github.com/Hackl0us/SS-Rule-Snippet/wiki/Quantumult 中步骤 4 ~ 5。
