### ISSUE TITLE
一个关于 Workflow 的建议

### ISSUE THREAD

**Issue by OiCkilL** [Hackl0us/SS-Rule-Snippet#28]
Workflow 是不错的，不过推荐把自定义字段分得更细点。 [Host]  [URL Rewrite] [SSID Setting] 等字段最好可以单独自定义添加。因为这些都不是 [Rule] 里面的

另外，conf 文件的命名有问题，存出来的文件是带斜杠的：
Hackl0us-Rules-2018_05_23-11/31.conf
尝试使用的时候，没法存到 Surge 目录

**Comment by Hackl0us** [comment]
感谢您的建议，我最近会逐渐完善 Workflow。那个 conf 文件的命名应该是意外，我会尽快修改。

**Comment by byhooi** [comment]
把host，URL，ssid填在Proxy，Proxy Group那里，别填在补充规则那里就可以了。

**Comment by Hackl0us** [comment]
正如楼上所说，您可以把补充规则填写在 Proxy / Proxy Group 的框内。但是仍然可能存在规则冲突的问题，这个项目即将启动 3.0，会完全避免您提及的问题。请您期待。
