### ISSUE TITLE
// 注释 Surfboard 会报错等问题

### ISSUE THREAD

**Issue by Hayxi** [Hackl0us/SS-Rule-Snippet#29]
建议添加 services.googleapis.cn 为代理，不然 Google Play Store 无法下载应用。
另外，规则连接不上 FCM，我正在找寻解决办法。

**Comment by Hackl0us** [comment]
非常感谢反馈，因为本人没有安卓设备，所以可能需要您和其他安卓用户测试。我会立刻进行修改。

**Comment by Hayxi** [comment]
@Hackl0us 的确有问题，有些域名设置直连也会走代理。
