### ISSUE TITLE
您好，能不能麻烦您写一个 Potatso 2 的规则导入方式？

### ISSUE THREAD

**Issue by liberalisman** [Hackl0us/SS-Rule-Snippet#30]
您好，能不能麻烦您写一个 Potatso 2 的规则导入方式？不了解该如何操作，拜托了🙏。

**Comment by Hackl0us** [comment]
您好，现在已经支持 Workflow 直接导入了，您可以看一下项目主页的说明部分。先在 App Store 下载 Workflow 然后点击表格中的链接就行。

**Comment by liberalisman** [comment]
workFlow 写了步骤，并没有 URL 以及具体的教程，实在看不懂啊。。。真不好意思
