### ISSUE TITLE
workFlow 的 Open in ... 命令，不允许在 WorkFlow 中打开

### ISSUE THREAD

**Issue by liberalisman** [Hackl0us/SS-Rule-Snippet#31]
workFlow 的 Open in ... 命令，不允许在 WorkFlow 中打开，不知道是不是 Potatso 的限制。

**Comment by Hackl0us** [comment]
Potatso 已经很久没有更新了，作者一直在更新 Potatso Lite（完全免费），推荐您使用这个工具，然后开启 智能路由 功能，不需要任何规则支持。项目不打算支持 Potatso 2 了。
