### ISSUE TITLE
转换为 win-ssr 的规则，应该怎么做？

### ISSUE THREAD

**Issue by allenchennnn** [Hackl0us/SS-Rule-Snippet#32]
mac ios android 上的客户端规则都有人维护了，唯独 win 上没有。
win-ssr 的客户端的规则只支持 域名 和 IP .
该如何改造您的规则呢？

**Comment by Hackl0us** [comment]
实际上这个确实是一个问题，因为 Window 上没有类似 Surge 这样的工具，所以大家一直使用 GFWList 这样的规则。我的规则并不容易转换成支持 Windows SSR 这样的规则。但是有类似的更好的规则您可以参考使用，https://github.com/ACL4SSR/ACL4SSR
