### ISSUE TITLE
萌新提问

### ISSUE THREAD

**Issue by fghtingskr** [Hackl0us/SS-Rule-Snippet#33]
大佬你好，第一次使用规则，我想知道，我第一次添加您的规则后，当后来某天您更新了您的规则，那么我还用重新workflow添加一次规则吗？

**Comment by Hackl0us** [comment]
对，您需要重新使用 Workflow 获取规则并覆盖原来的规则。这个时候就需要注意备份一下，对于 Surge 就要备份节点配置信息。Quantumult 可以选择是否更新服务器信息，选择忽略就行。Shadowsocks 和 Potatso 2 的配置文件和节点信息是独立的，所以不影响。
