### ISSUE TITLE
去掉默认的 surge 的远程管理密码？

### ISSUE THREAD

**Issue by zhuangya** [Hackl0us/SS-Rule-Snippet#35]
https://github.com/Hackl0us/SS-Rule-Snippet/blob/d48b12005d058417b5a60787d63a5e50f2c24efe/LAZY_RULES/Surge.conf#L12-L13

这里留一个默认的密码在配置文件里面可能会造成一些安全隐患

**Comment by Hackl0us** [comment]
其实问题不大，因为一般来讲是这个密码仅在本机启动监听，所以即使使用默认密码不是什么问题。来自于外网的用户基本上没有办法连接上来。
但是我已经采纳您的建议，已经将默认密码抹去了。
