### ISSUE TITLE
希望能添加对Mac端Reborn的支持

### ISSUE THREAD

**Issue by EGOISTK21** [Hackl0us/SS-Rule-Snippet#36]
Reborn项目地址https://github.com/langyanduan/Reborn
Reborn详细规则https://github.com/langyanduan/Reborn/blob/master/v2/DETAIL.md

**Comment by Hackl0us** [comment]
感谢提供，考虑很久，最后决定暂时没有计划支持 Reborn，因为是一个相对于 Surge、Clash 来说比较小众的软件。而且会为维护增加更多成本。

macOS 目前比较推荐 ClashX，因为功能全面，还包括了支持 DoT 的 DNS，而且也推出了类似 Dashboard 的功能。
