### ISSUE TITLE
iphone XR上加载surge规则后siri无法使用

### ISSUE THREAD

**Issue by Jin6** [Hackl0us/SS-Rule-Snippet#39]
不知道为什么，请检查下

**Comment by Hackl0us** [comment]
您好，我这边测试一切正常。我的 Surge 是 TestFlight 版本。
但是您说的问题的确我曾经也遇到过。个人觉得和规则关系不大，因为我测试过其他的一些规则，也不能解决这个问题。
目前怀疑是 NetworkExtension 的问题。您的 Surge 是否是 TestFlight 版本？如果不是，建议更新到最新的测试版，再观察问题是否存在。

**Comment by Jin6** [comment]
试过了，surge 2.6.8， ios 12.01（ipohne XR & ipad pro），打开surge，siri就失效，不关规则的事。

**Comment by Hackl0us** [comment]
感谢反馈，感觉这个问题断断续续的。还需要后期 Apple 或者开发者进行修复。
问题关闭。
