### ISSUE TITLE
请添加 smzdm.com 为 DIRECT

### ISSUE THREAD

**Issue by Mongkii** [Hackl0us/SS-Rule-Snippet#40]
```
DOMAIN-SUFFIX,smzdm.com,DIRECT
```

**Comment by Hackl0us** [comment]
这个地址经过测试确认不受任何影响。因为它的域名可以被解析成中国 IP，因此没有这条规则也会直连。

**Comment by Mongkii** [comment]
经测试，使用 Shadowrocket 懒人包默认配置，网络为上海电信的情况下，部分 smzdm 网址走了代理
![77739268-01e9-44d3-b6f2-d4d19db4a32c](https://user-images.githubusercontent.com/8596458/47698368-0be44500-dc4a-11e8-8eb7-16151f15cc51.png)

**Comment by Hackl0us** [comment]
小火箭真是个神奇的工具。
问题已经了解，我会在下一个版本中添加相关域名和规则。感谢反馈。
