### ISSUE TITLE
clashx懒人规则误伤ourbits

### ISSUE THREAD

**Issue by cpaig** [Hackl0us/SS-Rule-Snippet#46]
DOMAIN-SUFFIX,club,REJECT会导致[https://ourbits.club](https://ourbits.club)进不去

**Comment by Hackl0us** [comment]
了解，我应该把这个规则移除，因为 club 这个关键词可能会误伤一大批域名。感谢反馈。

**Comment by Hackl0us** [comment]
问题已经修正，请更新配置文件，感谢。
