### ISSUE TITLE
找了半天没找到shuttle的规则...

### ISSUE THREAD

**Issue by hd5970** [Hackl0us/SS-Rule-Snippet#48]

**Comment by Hackl0us** [comment]
非常抱歉，因为项目一开始计划支持 shuttle，但是因为 shuttle 规则比较复杂，和 SS Rule Generator 对接起来也比较费劲，而且目前 clash 发展相当不错，简单易用，衍生版本极多，便于维护，功能全面。项目不打算支持 Shuttle，推荐您使用 Clash.
