### ISSUE TITLE
可以提供 speedtest 测速的规则吗？

### ISSUE THREAD

**Issue by MF-x** [Hackl0us/SS-Rule-Snippet#49]
每次用speedtest给节点测速的时候，还要开一次全局，太麻烦了，如果有规则，直接切换就好了。

**Comment by Hackl0us** [comment]
你好，如您所描述。Speedtest 默认就是的规则就是直连，用来获取当前网络的带宽速度，并不推荐直接走代理。而由 Netflix 提供的 fast.com 则默认是代理，用来查看代理速度的。
如果您希望 Speedtest 测试代理服务器速度，我推荐使用全局模式测试。这样测得的结果也比较准确。
