### ISSUE TITLE
pinterestAPP和网站出现加载全是空白的问题，B站的‘我的账号’页面，ipad版B站app的‘我的追番’页面加载不出来

### ISSUE THREAD

**Issue by xk1357240** [Hackl0us/SS-Rule-Snippet#53]
多次刷新后或者重新打开app、重新连接代理可以解决，但以上3个问题很容易复现，设备ipad pro，工具shadowrocket

**Comment by xk1357240** [comment]
发现是连接公共wifi导致dns存在问题所致，手动设置公共wifi的dns问题解决，但是为什么shadowrocket配置文件的dns覆写没有生效呢？

**Comment by Hackl0us** [comment]
您可以尝试将配置文件中的 DNS 一行，`system` 删掉。尝试问题是否解决。

**Comment by xk1357240** [comment]
重新描述一下问题，pinterest应该是正常的。b站app在公共wifi下加载不成功。切换小火箭默认配置也是这个问题。
把配置文件里的dns删掉了system，也删了国外的，只留114和阿里的。
不论代理模式是配置还是直连，通过b站网页诊断能捕捉到问题
![pic1](https://i.loli.net/2019/01/28/5c4ee71b46e48.png)
![pic2](https://i.loli.net/2019/01/28/5c4ee71b79457.png)
![pic3](https://i.loli.net/2019/01/28/5c4ee8d17222a.png)
但这个诊断页面跟实际访问的情况也有不对应的时候。。。
![pic4](https://i.loli.net/2019/01/28/5c4ee8a7cb2c3.png)
此时app访问正常。
公共wifi还是不适合挂代理...

**Comment by Hackl0us** [comment]
我是用的代理工具是 Surge，测试后没有任何问题。
这个问题也可能取决于当地运营商。

<img width="931" alt="snipaste_2019-01-29_11-29-07" src="https://user-images.githubusercontent.com/10215166/51883151-b0e2fb00-23bc-11e9-927b-ae4d750049a6.png">
