### ISSUE TITLE
在iPad上，Netflix 不开全局不能播放视频

### ISSUE THREAD

**Issue by wang93wei** [Hackl0us/SS-Rule-Snippet#57]
问题如题
但是在iPhone上就没有遇到过这个问题，

**Comment by Hackl0us** [comment]
您好，我个人认为是您的规则问题。
因为 Netflix 域名即使不添加也会默认走 Final 规则。

请您检查：
1. iPad 使用的节点是否支持看 Netflix
2. iPad 的规则和语法是否符合代理工具。

问题应该不在于规则。
