### ISSUE TITLE
Clash 的 load-balance 策略组在最新的 ClashX 上会出现问题。

### ISSUE THREAD

**Issue by GetToSet** [Hackl0us/SS-Rule-Snippet#58]
Clash 配置的 load-balance 策略组在最新的 ClashX 上会出现问题，提示缺少 url 配置项。

**Comment by Hackl0us** [comment]
请您尝试更新 ClashX 的版本，问题应该不在于规则。
规则的配置格式直接取自 https://github.com/Dreamacro/clash#config
