### ISSUE TITLE
建议snapdrop.net加入直连

### ISSUE THREAD

**Issue by sakuyamaij** [Hackl0us/SS-Rule-Snippet#61]
作为一个局域网内的p2p文件传输平台，默认域名走代理会导致设备之间无法找到。
需直连才能正常工作
`- DOMAIN,snapdrop.net,DIRECT`
还有这个站，默认解析国外ip，无法访问
`- DOMAIN,www.zhuihd.com,DIRECT`
二次元麻将页游雀魂，也是默认会走代理造成卡
`- DOMAIN-KEYWORD,majsoul,DIRECT`

**Comment by Hackl0us** [comment]
感谢您的反馈
已经增加 snapdrop.net 的直连策略。
zhuihd.com 并没有成功解析，即使直连也是如此，因此不给予采纳。
二次元麻将页游雀魂 不是大众常用的网站，您可以 fork 本项目或自行加入该规则，项目暂时不急于采纳。
非常感谢！
