### ISSUE TITLE
建议修正academic list具体内容

### ISSUE THREAD

**Issue by vhvg** [Hackl0us/SS-Rule-Snippet#62]
在 https://github.com/Hackl0us/SS-Rule-Snippet/blob/master/Rulesets/Custom/academic.list 中，最后一条规则后写入了 DOMAIN-KEYWORD,sci-hub,Proxy 会导致RULE-SET引用报错
因此希望去掉此条规则

**Comment by winduser** [comment]
https://github.com/Hackl0us/SS-Rule-Snippet/pull/63

我把你的意见 pull request 上去了。

**Comment by Hackl0us** [comment]
非常感谢二位，Request 已采纳。
