### ISSUE TITLE
建议增加 mmstat.com 直连

### ISSUE THREAD

**Issue by xatec** [Hackl0us/SS-Rule-Snippet#70]
该域名为淘宝网所使用。

子域名为：

gm.mmstat.com
log.mmstat.com
oneid.mmstat.com

如果不直连将会拖慢淘宝网的打开速度。

**Comment by winduser** [comment]
*.mmstat.com 是阿里巴巴旗下产品的数据统计域名，应当 reject 吧？

**Comment by xatec** [comment]
@winduser 反正只要走代理就非常卡。

**Comment by Hackl0us** [comment]
综合上述两位的描述和我自己的调研，提供的域名是属于广告追踪类的域名。所以决定采用 REJECT 策略。感谢 @winduser @xatec 的信息。

**Comment by samurai00** [comment]
根据属性确实应该reject，但貌似因为阿里拒绝会不停重试还是啥，反正最终会导致app/小程序加载特别慢特别卡。

**Comment by liby** [comment]
现在更加恶劣，像我发现，如果 REJECT 了其相关域名，直接进不去闲鱼的一些付款页面

![telegram-cloud-photo-size-5-6096087086441542389-y](https://user-images.githubusercontent.com/38807139/206605520-8b9dec86-4f9c-412d-b86c-dd68f7badb24.jpg)

**Comment by tooadstool** [comment]
REJCET之后无法播放优酷视频

![image](https://github.com/Hackl0us/SS-Rule-Snippet/assets/26811405/5e13fc40-caf1-4f90-a725-936846b4300e)

![image](https://github.com/Hackl0us/SS-Rule-Snippet/assets/26811405/057a2ee0-f6b9-4021-978d-9960393caf4f)

**Comment by 8764zui** [comment]
不应该reject，会导致很多网站打不开。

<img width="1649" height="1107" alt="Image" src="https://github.com/user-attachments/assets/8d85aba1-ed42-4816-b299-0012498f1f68" />
