### ISSUE TITLE
请问使用本项目SURGE3捷径导入的规则显示“规则#3使用了一个位置的策略：proxy”怎么解决？

### ISSUE THREAD

**Issue by Billie-Chou** [Hackl0us/SS-Rule-Snippet#71]

**Comment by Billie-Chou** [comment]
作者你好，我研究了半天不知道什么原因，想请问下，这是我VPN的设置问题还是规则的问题啊？

**Comment by Hackl0us** [comment]
这个很明显是你的代理服务器配置的问题。应该是服务器的格式不正确。Surge 3 的服务器格式和 Surge 2 及更低版本不一样。建议去官方手册查找一下正确格式。https://manual.nssurge.com/policy/proxy.html
