### ISSUE TITLE
请问 🚀 SS Rule Generator 🚁 这个工具网页是同步更新的吧？

### ISSUE THREAD

**Issue by nlnlnull** [Hackl0us/SS-Rule-Snippet#72]
还可以使用 [🚀 SS Rule Generator 🚁](https://hackl0us.com/project/ss-rule-generator/) 这个工具网页生成规则么？和捷径的效果是一样的吧？

**Comment by Hackl0us** [comment]
您好，这个工具其实我有好一段时间没有维护了，我还是推荐您暂时使用捷径来更新。我找时间会更新一下这个网页版本的制作工具。
