### ISSUE TITLE
new function "fallback-filter:"

### ISSUE THREAD

**Issue by wangxin6** [Hackl0us/SS-Rule-Snippet#73]
clash增加新的功能：
   fallback-filter:
     geoip: true # default
     ipcidr: # ips in these subnets will be considered polluted
       - 240.0.0.0/4

**Comment by Hackl0us** [comment]
非常感谢您的反馈， 我已经将最新版本的 clash 配置文件和相关汉化在本地更新了。将在数天后和开屏广告一起推送上去。
其中有一点不是很理解，geoip: true 的作用是什么呢？因为官方文档没有解释，如果改为 false 会有怎样的影响呢？

**Comment by wangxin6** [comment]
抱歉，我不了解。请其他人解释一下吧。

**Comment by Hackl0us** [comment]
已经添加相关模板，感谢。

**Comment by Kevin-Vibe** [comment]
> 非常感谢您的反馈， 我已经将最新版本的 clash 配置文件和相关汉化在本地更新了。将在数天后和开屏广告一起推送上去。
> 其中有一点不是很理解，geoip: true 的作用是什么呢？因为官方文档没有解释，如果改为 false 会有怎样的影响呢？

@Hackl0us 官方文档有写。

>  # If IP addresses resolved with servers in `nameservers` are in the specified
>   # subnets below, they are considered invalid and results from `fallback`
>   # servers are used instead.
>   #
>   # IP address resolved with servers in `nameserver` is used when
>   # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
>   #
>   # If `fallback-filter.geoip` is false, results from `fallback` nameservers
>   # are always used, and answers from `nameservers` are discarded.
>   #
>   # This is a countermeasure against DNS pollution attacks.
> 

如果改为 false，则所有 DNS 解析请求都会交由 fallback servers 完成。
