### ISSUE TITLE
clash yaml 规则里面添加的 apple 配置是不是有问题？

### ISSUE THREAD

**Issue by Fimreal** [Hackl0us/SS-Rule-Snippet#75]
默认写的
```
- DOMAIN-SUFFIX,apps.apple.com,Proxy
```
这是认真的吗，让 apps.apple.com 默认走 proxy ？这规则要多吞多少流量啊。

**Comment by Hackl0us** [comment]
你觉得这个规则会吞多少流量？为什么会吞流量？

这个规则存在的意义是以前的 itunes.apple.com 的网页版显示 App 详细信息的域名被换成了 apps.apple.com
