### ISSUE TITLE
建议添加 discord 代理

### ISSUE THREAD

**Issue by GhostwithBlade** [Hackl0us/SS-Rule-Snippet#78]
DOMAIN-SUFFIX,discord.gg,Proxy
DOMAIN-SUFFIX,discordapp.com,Proxy
DOMAIN-SUFFIX,discordapp.net,Proxy

**Comment by Hackl0us** [comment]
感谢提供相关域名，Discord 的确是游戏玩家常用的即时消息工具，给予采纳，感谢～

**Comment by Hackl0us** [comment]
Discord 暂时以规则片段的形式存在。RuleSet/App/Social/Discord.list 下
