### ISSUE TITLE
请教：均衡负载写法

### ISSUE THREAD

**Issue by ntgeralt** [Hackl0us/SS-Rule-Snippet#80]
你好，请教一下
我使用你例程
`- { name: "PROXY", type: url-test, proxies: ["1", "2", "3"], url: "https://www.bing.com", interval: 300 }`

发现他一直只用第一节点，请问我哪里操作有误~
ps：我在路由器上尝试多节点均衡负载

**Comment by sdc6882278** [comment]
因为urltest策略启用是测试服务器响应最快的一个，而不是负载均衡。
2019年11月14日 +0800 PM8:37 Geralt <notifications@github.com>，写道：

**Comment by ntgeralt** [comment]
不是……我用上面他似乎只用第一个节点，哪怕第一个节点连不上

之后用下面解决了
`
- name: "PROXY"
  type: url-test
  proxies:
    - "1"
    - "2"
    - "3"
    - "4"
  url: 'http://www.gstatic.com/generate_204'
  interval: 300

`
