### ISSUE TITLE
请问ClashXR的SSR配置怎么写？

### ISSUE THREAD

**Issue by alpha87** [Hackl0us/SS-Rule-Snippet#82]
请问ClashXR的SSR配置怎么写？听说ClashXR支持SSR，但是一直没看到示例配置。谢谢！

**Comment by Hackl0us** [comment]
抱歉这个项目仅参考支持 Clash 和 ClashX，我没有看过也没有使用过 ClashXR。
你可以参考一下 ClashXR 官方的文档。但是理论来讲配置文件应该差别不大，除了服务器配置部分，其他部分应该可以直接用。
