### ISSUE TITLE
clashx不识别proxy

### ISSUE THREAD

**Issue by An0nymous0** [Hackl0us/SS-Rule-Snippet#83]
![image](https://user-images.githubusercontent.com/6836030/70682297-679c5100-1cd9-11ea-907a-d5f2050e1e61.png)

不识别 Proxy
- DOMAIN-SUFFIX,9to5mac.com,Proxy

提示 not found proxy

**Comment by Hackl0us** [comment]
因为你的策略组没有定义 Proxy，和我的规则模板无关。
