### ISSUE TITLE
ProxyGroup: `url` or `interval` missing

### ISSUE THREAD

**Issue by liby** [Hackl0us/SS-Rule-Snippet#86]
masOS: 10.15.2
ClashX Version: 1.16.9

Error Message:

> ProxyGroup[x]: `url` or `interval` missing

**Tentative solution:**
-  
  ```
  # load-balance 可以使相同 eTLD 请求在同一条代理线路上
  # - { name: "load-balance", type: load-balance, proxies: ["xxx"] }
  ```
  or
  ```
  # load-balance 可以使相同 eTLD 请求在同一条代理线路上
  - { name: "load-balance", type: load-balance, proxies: ["xxx"], url: "https://www.bing.com", interval: 300 }
  ```

![image](https://user-images.githubusercontent.com/38807139/71480798-f78fde00-2835-11ea-98e5-7471f99b71e6.png)

**Problem:**
- 懒人规则的这里是不是漏掉了 `url` 和 `interval`?

**Comment by Hackl0us** [comment]
非常感谢，我会在下次推送中修复这个问题。
