### ISSUE TITLE
Amp CDN出错

### ISSUE THREAD

**Issue by offferu** [Hackl0us/SS-Rule-Snippet#89]
例如
https://gizmodo-com.cdn.ampproject.org/v/s/gizmodo.com/the-biggest-problems-with-bluetooth-audio-are-about-to-1840461602/amp?amp_js_v=a2&amp_gsa=1&usqp=mq331AQCKAE%3D#referrer=https%3A%2F%2Fwww.google.com&amp_tf=From%20%251%24s&ampshare=https%3A%2F%2Fgizmodo.com%2Fthe-biggest-problems-with-bluetooth-audio-are-about-to-1840461602

打不开链接，
请问你们的正常吗？

多谢！

**Comment by Hackl0us** [comment]
我可以正常访问，完全没有问题。
