### ISSUE TITLE
有关ClashX懒人规则导入的代码

### ISSUE THREAD

**Issue by Kawaii-KM** [Hackl0us/SS-Rule-Snippet#91]
在执行代码最后的`open`时出现了错误提示
![屏幕快照 2020-01-31 13 10 57](https://user-images.githubusercontent.com/56059155/73514094-4c250b00-442b-11ea-8753-beafb6e53d71.png)

可以改成`open $HOME/.config/clash/`

**Comment by Hackl0us** [comment]
您是不是少复制了一个 .

我记得命令是这样
`cd $HOME/.config/clash`
`open .`  <-- 这个命令是调用 Finder 来打开当前文件夹。
