### ISSUE TITLE
规则格式有问题

### ISSUE THREAD

**Issue by zqjimlove** [Hackl0us/SS-Rule-Snippet#92]
https://raw.githubusercontent.com/Hackl0us/SS-Rule-Snippet/master/LAZY_RULES/clash.yaml

153 行的  - name: "vmess" 缩进不对，导致无法解释

**Comment by zqjimlove** [comment]
建议添加以下规则，osx下有可能会导致丢流量……
  - 'DOMAIN-SUFFIX,safebrowsing.googleapis.com,DIRECT'

**Comment by Hackl0us** [comment]
非常感谢您提出的更正。我已经在修改。
另外我想问一下，macOS 下丢流量是什么情况？
这个域名看起来，是 Safari 浏览器用来判断用户浏览网页是否为恶意网址的查询链接。
如果不添加这个规则会导致怎样的问题呢？

**Comment by zqjimlove** [comment]
其实是那天我发现我的流量突然没了1T，之后排查发现系统从safebrowsing.googleapis.com一直在几m的下载些东西，当时并没有打开Safari浏览器 ，同时我google后发现部份人也会有这种情况。

**Comment by Hackl0us** [comment]
非常感谢您提出的建议，我已经完成了调查并添加了所有相关域名和服务。

导致这个问题的原因是：如果 iOS / macOS 操作系统的“国家或地区“设置为中国大陆，那么 Safari 会请求 safebrowsing.urlsec.qq.com 和 safebrowsing.googleapis.com 去下载欺诈网站的数据库，并且可能会发送用户的 IP 地址等浏览信息。如果是非中国大陆，则只向 safebrowsing.googleapis.com 请求下载数据。

这个操作可能会引起两个问题，一个是按照默认规则来看，这个过程会消耗大量的代理流量，也就是您描述的现象。第二个是，腾讯的网站数据库会阻碍我们浏览成人网站，而且会发送一些信息到腾讯，我并不相信腾讯。

为了彻底禁止这个功能，您可以可以进入 Safari 设置中 Security 项目，关闭 Fraudulent Website Warning 功能后，将两个域名的策略手动设置为 REJECT。

**Comment by zqjimlove** [comment]
厉害，调查得很详细学习了。感谢给出的建议，我通过手动的方式添加这个规则。再次感谢

**Comment by Hackl0us** [comment]
更新规则后，就会自动包含了这两个域名的 DIRECT 策略～感谢提出建议，如果有更好的建议，欢迎随时开 Issue ，谢谢
