### ISSUE TITLE
clash安卓版错误

### ISSUE THREAD

**Issue by Zhu-Rookie** [Hackl0us/SS-Rule-Snippet#93]
在新建profile，并导入配置时，遇到错误：Invaild Config: ProxyGroup Proxy:'proxies' is not a slice，希望能指正解决，谢谢

**Comment by Hackl0us** [comment]
你要确认你配置的 Proxy 和 Proxy Group 语法是正确的，而且 Proxy Group 里面要包含你定义的 Proxy。
每一条规则后面，使用的是你 Proxy 和 Proxy Group 里面定义的名字，而不是写死的 Proxy
