### ISSUE TITLE
ClashX for mac 配置错误

### ISSUE THREAD

**Issue by imsoso** [Hackl0us/SS-Rule-Snippet#95]
Version 1.17.3
载入 https://github.com/Hackl0us/SS-Rule-Snippet/commit/c61ca046ce55a552fdda4fbf15ed6746bc2df140 的配置后 
提示 211 行错误

修改缩进以后，又提示 uuid 错误

**Comment by sxiaojian88** [comment]
同遇到

**Comment by Hackl0us** [comment]
配置文件缩进的问题已经解决了，请更新配置文件来解决问题。
关于 UUID 的问题，和配置文件没有关系，请参考 clash 官方配置规范和语法，可尝试在 UUID 用英文双引号包裹。
