### ISSUE TITLE
建议移除academic.list中的scihub

### ISSUE THREAD

**Issue by luanshixiao** [Hackl0us/SS-Rule-Snippet#97]
scihub本就是在没有高校图书馆资源的时候下载文献的方法，因此当academic.list设置为DIRECT时，scihub无法代理，常常会被墙。建议移除scihub这一条，将其放入国外域名，更适合使用逻辑。

**Comment by Hackl0us** [comment]
现在学术网站的 list 已经被切割为 直连 和 代理两部分。
我记得 scihub 被设置成直连的原因，好像是有人说这个有些高校会购买这个网站的一些版权，所以在直连的时候，可以直接使用特殊的账户下载文献。
因为个人不使用这个网站，所以我现在有点疑惑，究竟这个 scihub 应该怎么分？

**Comment by luanshixiao** [comment]
> 现在学术网站的 list 已经被切割为 直连 和 代理两部分。
> 我记得 scihub 被设置成直连的原因，好像是有人说这个有些高校会购买这个网站的一些版权，所以在直连的时候，可以直接使用特殊的账户下载文献。
> 因为个人不使用这个网站，所以我现在有点疑惑，究竟这个 scihub 应该怎么分？

scihub本质就是盗版，所有人都能免费下载，不需要走校园网的授权。
且其服务器在海外，偶尔会被墙，所以scihub一般情况肯定是走代理比较好。
综上scihub应该移出academic-direct，不与其他需要走校园网的期刊网站放在一起。

**Comment by Lolisky** [comment]
是的，sci-hub不是“可购买、根据ip授权”的数据库，而是为绕过购买和授权而生的，建议作为直连域名。

**Comment by Hackl0us** [comment]
@Lolisky 
> 是的，sci-hub不是“可购买、根据ip授权”的数据库，而是为绕过购买和授权而生的，建议作为直连域名。

@luanshixiao 
> 且其服务器在海外，偶尔会被墙，所以scihub一般情况肯定是走代理比较好。

感谢二位的回复，但是你们的回复依然有冲突。如果服务器的确在海外，二位没有争议的话，我打算把它放在代理的 list 里面。

**Comment by Lolisky** [comment]
@Hackl0us 
> 你们的回复依然有冲突。
是我表述有误，scihub确实应当通过代理连接。
我当时正在看用于教育网代理的规则，在那个语境下，学校购买的数据库是需代理域名，scihub则从本地连接，于是就说混了 :(
