### ISSUE TITLE
是否可以单独为 Apple 增加一个策略？

### ISSUE THREAD

**Issue by nlnlnull** [Hackl0us/SS-Rule-Snippet#99]
希望可以单独控制 Apple 的流量走直连或者代理，避免长时间挂全局的行为。

**Comment by Hackl0us** [comment]
Apple 本来就有单独的规则啊。
https://github.com/Hackl0us/SS-Rule-Snippet/blob/master/规则片段集/基础规则集/Apple服务优化.txt
